Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you 
might choose one over the other

Answer: Ordinal Encoding and Label Encoding are both techniques used to convert categorical variables into numerical representations.

Ordinal Encoding assigns unique integers to each category based on their order or rank, whereas Label Encoding assigns a unique integer to each category without considering any specific order.

When dealing with categorical variables that have an inherent order or rank, such as education levels (e.g., "High School," "Bachelor's," "Master's"), Ordinal Encoding is preferred. On the other hand, if there is no meaningful order among the categories, such as colors (e.g., "Red," "Blue," "Green"), Label Encoding is more appropriate.

Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in 
a machine learning project.



In [2]:
import pandas as pd

df = pd.DataFrame({
    'city' : ['New york' , 'London' ,'Paris' , 'Tokyo' , 'New york' , 'Paris'],
    'price' : [200 ,150,300,250,180,320]
})

In [3]:
df

city  price
0  New york    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New york    180
5     Paris    320

In [4]:
# calculate the mean price of each city

mean_price = df.groupby('city')['price'].mean().to_dict()

In [5]:
mean_price

{'London': 150.0, 'New york': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [6]:
# replace each city with its mean

df['city encoded'] = df['city'].map(mean_price)

In [7]:
df

city  price  city encoded
0  New york    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New york    180         190.0
5     Paris    320         310.0

Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

Answer: Covariance is a measure of the relationship between two random variables. It indicates the extent to which the variables change together. Covariance is crucial in statistical analysis as it helps identify the direction (positive or negative) and strength of the linear relationship between variables. It is calculated by averaging the product of the deviations of paired observations from their means.

Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium, 
large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library. 
Show your code and explain the output

In [5]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [6]:
df  = pd.DataFrame({
    'Color': ['red', 'green', 'blue'], 
    'Size':  ['small', 'medium', 'large'], 
    'Material' : ['wood', 'metal', 'plastic']
})

In [7]:
df

Color    Size Material
0    red   small     wood
1  green  medium    metal
2   blue   large  plastic

In [8]:
Encoder = LabelEncoder()

In [9]:
Encoder

LabelEncoder()

In [22]:
Encoder.fit_transform(df['Color'])

array([2, 1, 0])

In [23]:
Encoder.fit_transform(df['Size'])

array([2, 1, 0])

In [24]:
Encoder.fit_transform(df['Material'])

array([2, 0, 1])

Q6. You are working on a machine learning project with a dataset containing several categorical 
variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD), 
and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for 
each variable, and why

In [25]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

In [29]:
df = pd.DataFrame({
    'Education Level' : ['High School', 'Bachelors' , 'Masters' ], 
    'Employment Status' : ['Unemployed'  , 'Part-Time' , 'Full-Time']
})

In [30]:
df

Education Level Employment Status
0     High School        Unemployed
1       Bachelors         Part-Time
2         Masters         Full-Time

In [32]:
Encoder = OrdinalEncoder(categories = [['High School','Bachelors','Masters']])

In [38]:
Encoder.fit_transform(df[['Education Level']])

array([[0.],
       [1.],
       [2.]])

Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education 
level. Interpret the results

In [ ]:
import numpy as np
np.random.seed(42)
df = pd.DataFrame(np.random.randn(1000, 3),
                   columns=['Age', 'Income', 'Education'])
df.cov()

Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two 
categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
East/West). Calculate the covariance between each pair of variables and interpret the results

In [12]:




import pandas as pd

# Assuming you have your dataset in a pandas DataFrame
dataset = pd.DataFrame({
    'Temperature': [25, 28, 20, 22, 26],
    'Humidity': [60, 65, 70, 75, 80],
    'Weather Condition': ['Sunny', 'Cloudy', 'Rainy', 'Cloudy', 'Sunny'],
    'Wind Direction': ['North', 'South', 'East', 'West', 'North']
})

# Calculate the covariance matrix using pandas cov() function
covariance_matrix = dataset[['Temperature', 'Humidity']].cov()

# Print the covariance matrix
print("Covariance matrix between Temperature and Humidity:")
print(covariance_matrix)

# Calculate the covariance between Temperature and Weather Condition
covariance_temp_weather = dataset['Temperature'].cov(dataset['Weather Condition'])

# Print the covariance between Temperature and Weather Condition
print("\nCovariance between Temperature and Weather Condition:")
print(covariance_temp_weather)

# Calculate the covariance between Temperature and Wind Direction
covariance_temp_wind = dataset['Temperature'].cov(dataset['Wind Direction'])

# Print the covariance between Temperature and Wind Direction
print("\nCovariance between Temperature and Wind Direction:")
print(covariance_temp_wind)

# Calculate the covariance between Humidity and Weather Condition
covariance_humidity_weather = dataset['Humidity'].cov(dataset['Weather Condition'])

# Print the covariance between Humidity and Weather Condition
print("\nCovariance between Humidity and Weather Condition:")
print(covariance_humidity_weather)

# Calculate the covariance between Humidity and Wind Direction
covariance_humidity_wind = dataset['Humidity'].cov(dataset['Wind Direction'])

# Print the covariance between Humidity and Wind Direction
print("\nCovariance between Humidity and Wind Direction:")
print(covariance_humidity_wind)


Covariance matrix between Temperature and Humidity:
             Temperature  Humidity
Temperature         10.2      -5.0
Humidity            -5.0      62.5


TypeError: unsupported operand type(s) for /: 'str' and 'int'